# Generated by Django 2.2.4 on 2020-08-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
